# Generated by Django 3.1.3 on 2020-11-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('types', models.CharField(max_length=50, verbose_name='type')),
                ('genre', models.CharField(max_length=50, verbose_name='genre')),
                ('rank', models.IntegerField()),
                ('year_released', models.CharField(max_length=50, verbose_name='year')),
                ('image', models.ImageField(upload_to='', verbose_name=models.ImageField(default=None, upload_to=''))),
                ('ratings', models.FloatField()),
                ('rated', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('types', models.CharField(max_length=50, verbose_name='type')),
                ('genre', models.CharField(max_length=50, verbose_name='genre')),
                ('rank', models.IntegerField()),
                ('year_released', models.CharField(max_length=50, verbose_name='year')),
                ('image', models.ImageField(upload_to='', verbose_name=models.ImageField(default=None, upload_to=''))),
                ('ratings', models.FloatField()),
                ('rated', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('types', models.CharField(max_length=50, verbose_name='type')),
                ('genre', models.CharField(max_length=50, verbose_name='genre')),
                ('rank', models.IntegerField()),
                ('year_released', models.CharField(max_length=50, verbose_name='year')),
                ('image', models.ImageField(upload_to='', verbose_name=models.ImageField(default=None, upload_to=''))),
                ('ratings', models.FloatField()),
                ('rated', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
    ]
